server:
  port: 9090
  host: "0.0.0.0"
  health: "/admin/health"

2b:
  debug: true
  log: "./logs"
  jobs:
    - name: "hello-world"
      scripts: 
        - "echo 'Hello World'"
        - "echo 'Thanks for testing'"
        - "sleep 10"
        - "ls"
        - "cd ~"
    - name: "remote-world"
      path: "./scripts/remote-world.sh"