version: '2'

services:

  pinger-rs:
    container_name: pinger-rs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:9090
    image: rjmasikome/pinger-rs
